# Generated by Django 4.2.4 on 2023-09-07 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentAlocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Add Allocation',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Academic Semester',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Academic Session',
            },
        ),
        migrations.CreateModel(
            name='AcademicCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_Title', models.CharField(max_length=200)),
                ('course_Code', models.CharField(max_length=15)),
                ('credit_Hour', models.CharField(max_length=15)),
                ('allocate_Course', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='studentCourses.departmentalocation')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentCourses.semester')),
            ],
            options={
                'verbose_name_plural': 'Add Academic Course',
            },
        ),
    ]
