# Generated by Django 4.2.4 on 2023-09-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createquestion',
            old_name='name',
            new_name='name_Of_Department',
        ),
    ]
