# Generated by Django 4.2.4 on 2023-09-07 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0002_rename_name_createquestion_name_of_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createquestion',
            old_name='name_Of_Department',
            new_name='name_of_Department',
        ),
        migrations.AlterField(
            model_name='createquestion',
            name='course_Code',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='QuestionBank.code'),
        ),
        migrations.AlterField(
            model_name='createquestion',
            name='course_title',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='QuestionBank.course'),
        ),
    ]
