# Generated by Django 4.2.4 on 2023-08-18 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Level Of Study',
            },
        ),
        migrations.CreateModel(
            name='LocalGovernment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Local Government Origin',
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Nationality',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'State Of Origin',
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_Name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Name Of Village',
            },
        ),
        migrations.CreateModel(
            name='StudentBioData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriculation_No', models.CharField(max_length=200)),
                ('first_Name', models.CharField(max_length=200)),
                ('sure_Name', models.CharField(max_length=200)),
                ('other_Name', models.CharField(max_length=200)),
                ('year_in_school', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('Female', 'Female')], default=False, max_length=10)),
                ('phone_No', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(default=True, upload_to='profile_pic/Student/')),
                ('home_Address', models.CharField(max_length=40)),
                ('mother_Maiden_name', models.CharField(max_length=200)),
                ('local_Government', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.localgovernment')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.nationality')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.state')),
                ('village_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.village')),
            ],
            options={
                'verbose_name_plural': 'Students Personal Information',
            },
        ),
    ]
